steps:
  - imports:
      align: none
      list_align: with_alias
      pad_module_names: false
      long_list_align: new_line
      empty_list_align: right_after
      separate_lists: false

  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true

  # Replace tabs by spaces. This is disabled by default.
  - tabs:
      # Number of spaces to use for each tab. Default: 8, as specified by the
      # Haskell report.
      spaces: 8

  # Remove trailing whitespace
  - trailing_whitespace: {}

  # Squash multiple spaces between the left and right hand sides of some
  # elements into single spaces. Basically, this undoes the effect of
  # simple_align but is a bit less conservative.
  - squash: {}

columns: 80
newline: lf
